### ISSUE TITLE
reset API Header basic auth 

### ISSUE THREAD

**Issue by Eluso** [emqx/kuiper#573] opened 2020-10-29 03:33 UTC
![image](https://user-images.githubusercontent.com/20638270/97522094-e9709800-19d9-11eb-8616-46aaf8530e0f.png)
Set header auth use basic，get error "Stopped: rest sink property headers Authorization: Basic cm9vdDp0YW9zZGF0YQ== is not a map[string]interface."

create rule with text mode, running normal,but rule action was null
![image](https://user-images.githubusercontent.com/20638270/97522208-30f72400-19da-11eb-9493-cb264af7a04d.png)

![image](https://user-images.githubusercontent.com/20638270/97522298-68fe6700-19da-11eb-94be-5ec6ee8f9c1f.png)

**Comment by ysfscream** [comment] 2020-10-30 01:40
We should modify the type of `headers` field in the configuration file. It's not a `string` type, but should be `list_object`, and we can add custom key-value data.

**Comment by jinfahua** [comment] 2020-10-30 02:39
@EMQmyd please update the configuration file.

**Comment by jinfahua** [comment] 2020-11-13 01:07
@ysfscream Have you verified the issue? @EMQmyd Please close the issue if it's verified. Thanks.

**Comment by ysfscream** [comment] 2020-11-13 03:30
@jinfahua The correct data format is currently supported during configuration. But I can't reproduce this issue, could you please help test it again? @Eluso

**Closed** 2020-11-23 02:42 UTC
