### ISSUE TITLE
armv7  signal SIGSEGV

### ISSUE THREAD

**Issue by liyeqiang** [emqx/kuiper#584] opened 2020-11-03 01:50 UTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20553c]

goroutine 59 [running]:
runtime/internal/atomic.goStore64(0xf24514, 0x19000, 0x0)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:144 +0x1c
github.com/emqx/kuiper/xstream/nodes.(*DynamicChannelBuffer).SetLimit(...)
        /go/kuiper/xstream/nodes/dynamic_channel_buffer.go:29
github.com/emqx/kuiper/xstream/nodes.(*SourceNode).Open.func1.1(0xd3e640, 0xc8fc40, 0x83acf0, 0xf1e500, 0x83a600, 0xf1e080, 0xf243e0, 0xf36198, 0x0)
        /go/kuiper/xstream/nodes/source_node.go:123 +0xab0
created by github.com/emqx/kuiper/xstream/nodes.(*SourceNode).Open.func1
        /go/kuiper/xstream/nodes/source_node.go:79 +0x1e0

**Comment by liyeqiang** [comment] 2020-11-03 01:54
kuiper-1.0.0-linux-armv7l

**Comment by jinfahua** [comment] 2020-11-03 01:55
@ngjaying It seems the [same issue](https://github.com/emqx/kuiper/issues/570), could you please help to check it?

**Comment by ngjaying** [comment] 2020-11-03 02:22
Yes, I think this is a duplicate of #570

**Comment by jinfahua** [comment] 2020-11-03 03:27
@liyeqiang The problem has been fixed, and will be included in next version.

**Comment by liyeqiang** [comment] 2020-11-04 00:45
Thank you. When will the next version be released?

**Comment by jinfahua** [comment] 2020-11-04 00:50
> Thank you. When will the next version be released?

Maybe at the end of Nov.

**Comment by jinfahua** [comment] 2020-11-09 01:30
Close the issue.

**Closed by jinfahua** 2020-11-09 01:30 UTC
Labels: duplicate
